name: GO CI

on:
  push:
    paths:
      - 'golang/**'
      - '.github/workflows/go**'
  pull_request:
    paths:
      - 'golang/**'
      - '.github/workflows/go**'

jobs:

  matrix_build:
    runs-on: ${{ matrix.operating-system }}

    strategy:
      matrix:
        operating-system: [ubuntu-latest, macOS-latest,  windows-latest]
        go: [  '1.14', '1.13', '1.12' ]
    name: Go ${{ matrix.go }} Build on ${{ matrix.operating-system }}

    steps:
      - uses: actions/checkout@v1
      - name: Setup go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}

    #### BEGIN testify
      - name: run with testify
        working-directory: golang/testify
        run: go mod tidy && go test -v -run TestGen && go test -v -run TestSomething

      - name: assure one failing test
        working-directory: golang/testify
        run: "sh ../../scripts/assure_failing_test.sh 'go test -v' 'Error Trace:	kata_test.go:9'"
    #### END testify

    #### BEGIN testify test doubles
      - name: run with testify
        working-directory: golang/testify
        run: go mod tidy && go test -v -run TestStubIsReturningTrue && go test -v -run TestMockIsCalledWith42

      - name: assure one failing test
        working-directory: golang/testify
        run: "sh ../../scripts/assure_failing_test.sh 'go test -v TestMockIsFailingWhenNotCalledWith42' 'mock: Unexpected Method Call'"
    #### END testify  test doubles
