name: java

on:
  push:
    paths:
      - 'java/**'
      - '.github/workflows/java**'
  pull_request:
    paths:
      - 'java/**'
      - '.github/workflows/java**'

jobs:

  matrix_build:
    runs-on: ${{ matrix.operating-system }}

    strategy:
      matrix:
        operating-system: [ubuntu-latest, macOS-latest]
        #TODO fix: , windows-latest,
        java: [ 1.8, 11, 12, 13 ]
    name: Java ${{ matrix.java }} Build on ${{ matrix.operating-system }}

    steps:
      - uses: actions/checkout@v1
      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
    #### BEGIN assertJ
      - name: build assertJ with maven
        working-directory: java/assert_j
        run: mvn -B clean package --file pom.xml -Dtest=ThingTest\#it_should_not_fail

      # gradlew:
      - name: build with gradlew
        working-directory: java/assert_j
        run: ./gradlew test --warning-mode all --tests ThingTest.it_should_not_fail

      # gradle:
      - uses: eskatos/gradle-command-action@v1
        with:
          build-root-directory: java/assert_j
          gradle-version: current
          arguments: test --warning-mode all --tests ThingTest.it_should_not_fail
    #### END assertJ

    #### BEGIN cucumber
      - name: build cucumber with maven
        working-directory: java/cucumber
        run: mvn -B clean package --file pom.xml
    #### END cucumber

    #### BEGIN fitnesse
      - uses: eskatos/gradle-command-action@v1
        with:
          build-root-directory: java/fitnesse
          gradle-version: current
          arguments: test --warning-mode all
    #### END fitnesse

    #### BEGIN hamcrest
      - name: build hamcrest with maven
        working-directory: java/hamcrest
        run: mvn -B clean package --file pom.xml -Dtest=ThingTest\#it_should_not_fail

      # gradlew:
      - name: build with gradlew
        working-directory: java/hamcrest
        run: ./gradlew test --warning-mode all --tests ThingTest.it_should_not_fail

      # gradle:
      - uses: eskatos/gradle-command-action@v1
        with:
          build-root-directory: java/hamcrest
          gradle-version: current
          arguments: test --warning-mode all --tests ThingTest.it_should_not_fail
    #### END hamcrest

    #### BEGIN hue4j5
      - name: build hamcrest with maven
        working-directory: java/hue4j5
        run: mvn -B clean package --file pom.xml -Dtest=ThingTest\#it_should_not_fail
      # gradlew:
      - name: build with gradlew
        working-directory: java/hue4j5
        run: ./gradlew test --warning-mode all --tests ThingTest.it_should_not_fail

      # gradle:
      - uses: eskatos/gradle-command-action@v1
        with:
          build-root-directory: java/hue4j5
          gradle-version: current
          arguments: test --warning-mode all --tests ThingTest.it_should_not_fail
    #### END hue4j5

    #### BEGIN jqwik
      - name: build jqwik with maven
        working-directory: java/jqwik
        run: mvn -B clean package --file pom.xml

      # gradlew:
      - name: build with gradlew
        working-directory: java/jqwik
        run: ./gradlew test --warning-mode all

      # gradle:
      - uses: eskatos/gradle-command-action@v1
        with:
          build-root-directory: java/jqwik
          gradle-version: current
          arguments: test --warning-mode all
    #### END jqwik

    #### BEGIN junit4
      - name: build junit4 with maven
        working-directory: java/junit4
        run: mvn -B clean package --file pom.xml -Dtest=ThingTest\#it_should_not_fail
      # gradlew:
      - name: build with gradlew
        working-directory: java/junit4
        run: ./gradlew test --warning-mode all --tests ThingTest.it_should_not_fail

      # gradle:
      - uses: eskatos/gradle-command-action@v1
        with:
          build-root-directory: java/junit4
          gradle-version: current
          arguments: test --warning-mode all --tests ThingTest.it_should_not_fail
    #### END junit4

    #### BEGIN junit5
      - name: build junit5 with maven
        working-directory: java/junit5
        run: mvn -B clean package --file pom.xml -Dtest=ThingTest\#it_should_not_fail

      # gradlew:
      - name: build with gradlew
        working-directory: java/junit5
        run: ./gradlew test --warning-mode all --tests ThingTest.it_should_not_fail

      # gradle:
      - uses: eskatos/gradle-command-action@v1
        with:
          build-root-directory: java/junit5
          gradle-version: current
          arguments: test --warning-mode all --tests ThingTest.it_should_not_fail
     #### END junit5

    #### BEGIN mockito
      - name: build mockito with maven
        working-directory: java/mockito
        run: mvn -B clean package --file pom.xml -Dtest=ThingTest\#it_should_not_fail

      # gradlew:
      - name: build with gradlew
        working-directory: java/mockito
        run: ./gradlew test --warning-mode all --tests ThingTest.it_should_not_fail

      # gradle:
      - uses: eskatos/gradle-command-action@v1
        with:
          build-root-directory: java/mockito
          gradle-version: current
          arguments: test --warning-mode all --tests ThingTest.it_should_not_fail
    #### END mockito

    #### BEGIN spock
      - name: build spock with maven
        working-directory: java/spock
        run: mvn -B clean package --file pom.xml -Dtest=ThingSpec\#notfail
    #### END spock

    #### BEGIN truth
      - name: build truth with maven
        working-directory: java/truth
        run: mvn -B clean package --file pom.xml -Dtest=ThingTest\#it_should_not_fail
      # gradlew:
      - name: build with gradlew
        working-directory: java/truth
        run: ./gradlew test --warning-mode all --tests ThingTest.it_should_not_fail

      # gradle:
      - uses: eskatos/gradle-command-action@v1
        with:
          build-root-directory: java/truth
          gradle-version: current
          arguments: test --warning-mode all --tests ThingTest.it_should_not_fail
    #### END truth
