name: Scala CI

on:
  push:
    paths:
      - 'scala/**'
      - '.github/workflows/scala**'
  pull_request:
    paths:
      - 'scala/**'
      - '.github/workflows/scala**'

  schedule:
    # weekly build every FRI
    - cron: "0 6 * * 5"

jobs:

  matrix_build:
    runs-on: ${{ matrix.operating-system }}

    strategy:
      matrix:
        operating-system: [ ubuntu-latest ]
        # TODO fix me:  windows-latest, macOS-latest,
        java: [ 8, 10 ]
        # TODO fix me: 11, 12, 13
    name: Scala ${{ matrix.java }} Build on ${{ matrix.operating-system }}

    steps:
      - uses: actions/checkout@v2
      - name: Setup java
        uses: actions/setup-java@v2.5.0
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}

      - name: Run tests
        working-directory: scala/scalatest
        run: sbt test

      - name: Run tests
        working-directory: scala/scalatest-with-cats
        run: sbt "testOnly SomeOkTest"
